@startuml

title 商户终端绑定/解绑

database 数据库 as D #red




机构 -[#blue]> 商户前置: 请求

activate 商户前置

商户前置 -[#orange]> D: 查询机构信息，校验机构

note over 商户前置

RSA解密
RSA验签
字段校验

end rnote

商户前置 --[#ff6600]> 机构: 解密验签校验失败，直接返回

== 终端绑定start ==

商户前置 -[#orange]> D: 查询商户，校验商户

商户前置 -[#orange]> D: 查询厂商型号，校验厂商终端型号编号

商户前置 -[#orange]> D: 查询厂商，校验厂商编号

商户前置 -[#orange]> D: 查询终端，校验终端是否被其他商户绑定


商户前置 -[#blue]> 商户终端号生成服务
activate 商户终端号生成服务

商户终端号生成服务 -[#blue]>商户前置: 获取前置终端号

deactivate 商户终端号生成服务

商户前置 -[#blue]> 商户终端号生成服务
activate 商户终端号生成服务

商户终端号生成服务 -[#blue]>商户前置: 获取支付终端号

deactivate 商户终端号生成服务



deactivate 商户前置

note over 商户前置

请求参数有活动编号

end rnote

商户前置 -[#orange]> D: 查询活动，判断活动是否存在
商户前置 -[#orange]> D: 查询终端活动记录，判断终端是否已经绑定活动

商户前置 --> 机构: 判断信息失败返回

商户前置 -[#red]> D: 终端绑定关系入库
商户前置 -[#red]> D: 支付终端入库
商户前置 -[#red]> D: 活动存在，则绑定关系入库


== 终端绑定over ==

== 终端解绑start ==

商户前置 -[#orange]> D: 查询商户，校验商户

商户前置 -[#orange]> D: 查询商户终端，校验原商户终端关系是否存在

商户前置 --> 机构: 判断信息失败返回

商户前置 -[#red]> D: 删除商户终端关系
商户前置 -[#red]> D: 删除商户支付终端关系

== 终端解绑over ==

商户前置 -[#blue]> 机构

database 数据库 as D #red


@enduml